### ISSUE TITLE
1.14/1.15 update

### ISSUE THREAD

**Issue by Gjum** [Aleksey-Terzi/CombatRadar#2]
Ideally using Fabric, which seems to be the go-to modloader now even more so than 1.12 Liteloader because Forge 1.14 took so long to update.

**Comment by Aleksey-Terzi** [comment]
Sorry was busy this time.
Now upgraded to 1.18.2

**Comment by Aleksey-Terzi** [comment]
I was using Forge since it supports the latest MC and the most popular loader.
