### ISSUE TITLE
Unable to open radar settings

### ISSUE THREAD

**Issue by walkersgaming** [Aleksey-Terzi/CombatRadar#3]
Using 1.18.2 Fabric, I cannot see an option in controls to set a hotkey to open the menu, nor can I configure the mod in the ModMenu
![image](https://user-images.githubusercontent.com/14056973/169517764-ecfd2dc2-fcbd-4d74-bcd9-cfd6f36a0989.png)

**Comment by Aleksey-Terzi** [comment]
Ok, thanks, I'll look it.

**Comment by Aleksey-Terzi** [comment]
The bug is fixed.
Now hotkey can be changed via vanilla Key Binds menu:

![image](https://user-images.githubusercontent.com/5383652/169630634-891e3085-d0cb-4ffb-8fcc-098630744e96.png)

**Comment by Aleksey-Terzi** [comment]
Release is here: https://github.com/Aleksey-Terzi/CombatRadar/releases/tag/1.18.2-1.5
