### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by ryanmattt** [Aleksey-Terzi/CombatRadar#4]
-

**Comment by Aleksey-Terzi** [comment]
> but have you thought about putting this on CurseForge?

The number of mod users will increase significantly in this case, people will start asking questions and etc.
I will need to create a good guide.
I prefer to stay out of this :)

> I'd love to use it for a pack im currently making.

So, just include it, keep authorship and maybe link to github and that's it I guess.
If any bugs just create a new issue here, I will try to fix it when possible.
